cadastros/urls.py
from django.urls import path
from .views import CompraCreate, CompraUpdate, CompraDelete, CompraList, ProdutoCreate, ProdutoUpdate, ProdutoDelete, ProdutoList

urlpatterns = [
    path('cadastro/produto/', ProdutoCreate.as_view(), name="Cadastro Produto"),
    path('cadastro/compra/', CompraCreate.as_view(), name="Cadastro Compra"),
    path('editar/produto/<pk>', ProdutoUpdate.as_view(), name="Editar Produto"),
    path('editar/compra/<pk>', CompraUpdate.as_view(), name="Editar Compra"),
    path('excluir/produto/<pk>', ProdutoDelete.as_view(), name="Excluir Produto"),
    path('excluir/compra/<pk>', CompraDelete.as_view(), name="Excluir Compra"),
    path('listar/produto/', ProdutoList.as_view(), name="Listar Produto"),
    path('listar/compra/', CompraList.as_view(), name="Listar Compra"),
    
]

desafioWPensar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

paginas/urls.py
from django.urls import path
from .views import IndexView


urlpatterns = [#Serve para colocar os caminhos que o usuário terá que colocar para chegar em determinado site.
    path('',IndexView.as_view(), name=('index')), #Primeira tag seria o diretorio da pagina, a segunda o conteudo que vai aparecer e a terceira seria um nome para esse diretorio
]

usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name = 'usuarios/login.html'
    ), name="Login"),
    path('logout/', auth_views.LogoutView.as_view(), name="Logout"),
]

cadastros/models.py
from django.db import models
from django.db.models import Sum, Avg
from django.db.models.fields import DecimalField, IntegerField
from django.db.models.fields.related import ForeignKey
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
import itertools

# Create your models here.
def validate_not_spaces(value):
    if isinstance(value, str) and value.strip() == ' ':
        raise ValidationError(u"Você está tentando um valor em branco")


class Produto(models.Model):
    Nome = models.CharField(unique=True, blank=False, null=False, max_length=50, verbose_name="Nome Produto", validators=[validate_not_spaces])
    
    
    def quantidadeTotal(self):
        c = Compra.objects.values_list('produto').annotate(quantidadeSum = Sum('Quantidade'))
        c = list(itertools.chain(*c))
        d = 0
        s = self.id
        length = len(c)-1
        for x in range(length):
            if s == c[x]:
                d = c[(x+1)]

        return "{}".format(d)

    
    def precoMedioTotal(self,format=None):
        v = Compra.objects.values_list('produto').annotate(somaValor = Sum('Valor', output_field=DecimalField(decimal_places=2)))
        v = list(itertools.chain(*v))
        q = Compra.objects.values_list('produto').annotate(somaValor = Sum('Quantidade', output_field=DecimalField(decimal_places=2)))
        q = list(itertools.chain(*q))
        s = self.pk
        new = []
        vetorVazio = []
        length2 = len(v)
        for y in range(length2):
            if y % 2 == 0:
                new.append((v[y]))
            if y % 2 == 1:
                if q[y]>0:
                    new.append((v[y])/(q[y]))
                else:
                    new.append(0)
        
        length = len(new)-1
        if new == vetorVazio:
            d = 0
            return d
        else:
            for x in range(length):
                if s == new[x]:
                    d = new[(x+1)]
                    return "{}".format(round(d, 2))
                else:
                    d = 0
        return "{}".format(round(d, 2))
    
    def __str__(self):
        return "{}".format(self.Nome)

class Compra(models.Model):
    produto = ForeignKey(Produto, on_delete=models.CASCADE)
    Valor = models.DecimalField(blank=False,null=False, max_digits=7, decimal_places=2, default=0, validators=[MinValueValidator(0), MaxValueValidator(100000)], verbose_name="Preço Compra")
    Quantidade = models.PositiveIntegerField(blank=False, null=False, default=0 , validators=[MinValueValidator(1), MaxValueValidator(1000)], verbose_name="Quantidade Compra")
    PrecoMedio = models.FloatField(default=0, verbose_name="Preco Médio")
    
    @property
    def precoMedio(self):
        if self.Quantidade>0:
            c = (self.Valor/self.Quantidade)
            c = round(c, 2)
        else:
            c = 0
        return c

    def save(self, *args, **kwargs):
        self.PrecoMedio = self.precoMedio
        super(Compra, self).save(*args, **kwargs)

    

    def __str__(self):
        return "{}, ({}), ({})".format(self.produto, self.Valor, self.Quantidade)
    

paginas/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models

# Create your models here.

cadastros/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import Produto, Compra
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class ProdutoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('Login') 
    model = Produto #model seria o modelo que vc vai cadastrar/atualizar
    fields = ['Nome'] #campos a ser preenchidos
    template_name = 'cadastros/form-produto.html'
    success_url = reverse_lazy('Listar Produto')

class CompraCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('Login') 
    model = Compra
    fields = ['produto', 'Valor', 'Quantidade']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('Listar Compra')

class ProdutoUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('Login') 
    model = Produto
    fields = ['Nome']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('Listar Produto')

class CompraUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('Login') 
    model = Compra
    fields = ['produto', 'Valor', 'Quantidade']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('Listar Compra')

class ProdutoDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('Login') 
    model = Produto
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('Listar Produto')

class CompraDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('Login') 
    model = Compra
    template_name = 'cadastros/form-delete.html'
    success_url = reverse_lazy('Listar Compra')

class ProdutoList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('Login') 
    model = Produto
    fields = ['Nome']
    template_name = 'cadastros/lista-produto.html'

class CompraList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('Login') 
    model = Compra
    fields = ['produto', 'Valor', 'Quantidade']
    template_name = 'cadastros/lista-compras.html'

paginas/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):
    template_name = 'paginas/index.html'

usuarios/views.py
from django.shortcuts import render

# Create your views here.

cadastros/templates/cadastros/form-delete.html
{% extends 'paginas/base.html' %}

{% load static %}


{% block titulo %}
<title>Deletar {{ object }} ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="conteudo">
    <link rel ="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <div class="container-xl">
        <h3>Exclusão</h3>
        <p>Confirme se irá realizar esta operação</p>
        <hr>
        <form action="" method="POST">
        
            <p>
                Deseja excluir o registro: <strong>{{ object }}</strong>? <!--Object irá retornar o valor da função def__str__ do models.py-->
            </p>
        
            {% csrf_token %} <!--Validação de formulário do Django-->
        
            {{form.as_p}} <!--Tradução: Formulário em Paragrafo-->
        
            <button type="submit" class="btn btn-danger">Excluir</button>
        </form>
        
    </div>
</div>
{% endblock %}

cadastros/templates/cadastros/form-produto.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{{ form|as_crispy_errors }}

{% block titulo %}
<title>Cadastro Produto ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="formu">
    <div class="titulo-formu">
        <h1>Cadastro</h1>
        <hr>
    </div>
    <div class="div-formu">
        <form action="" method="POST">
            {% csrf_token %} <!--Validação de formulário do Django-->
                <ul>{{ form.non_field_errors }} </ul>
                <label for="id_Nome"> Nome: </label>
                <input type="text" name="Nome" maxlength="50" required id="id_Nome">
            <div class="btn-form"><button type="submit">Enviar</button></div>
        </form> 
    </div>   
</div>

{% endblock %}

cadastros/templates/cadastros/form.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}
{{ form|as_crispy_errors }}

{% block titulo %}
<title>Cadastro Compras ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="formu">
    <div class="titulo-formu">
        <h1>Cadastro</h1>
        <hr>
    </div>
    <div class="div-formu">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <label for="{{ field.id_for_label }}" class="label"> {{ field.html_name }} </label>
                {{ field }}
            {% endfor %}
            <div class="btn-form"><button type="submit">Enviar</button></div>
        </form> 
    </div>   
</div>

{% endblock %}

cadastros/templates/cadastros/lista-compras.html
{% extends 'paginas/base.html' %}

{% load static %}


{% block titulo %}
<title>Compras ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="conteudo">
    <link rel ="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<div class="container-xl" id="container-lista">
    <div class="table table-responsive">
        <h2>Lista de Compras:</h2>
        <hr>
        <table class="table table-striped" id="tabela">
            <tr>
                <th>Nome</th>
                <th>Valor</th>
                <th>Quantidade</th>
                <th>Preço Médio</th>
                <th>Opções</th>
            </tr>
            {% for Compra in object_list %} <!--Estrutura de repetição no django, bastante semelhante que em pyhon-->
            <tr>
                <td>
                    {{ Compra.produto }}
                </td>
                <td>
                    R$ {{ Compra.Valor }}
                </td>
                <td>
                    {{ Compra.Quantidade }} Unidades
                </td>
                <td>
                    R$ {{ Compra.PrecoMedio }}
                </td>
                <td>
                    <a href="{% url 'Editar Compra' Compra.pk %}" class="btn btn-warning btn-sm">Editar</a> <!--url é a forma de fazer o link-->
                    <a href="{% url 'Excluir Compra' Compra.pk %}" class="btn btn-danger btn-sm">Excluir</a> <!--url é a forma de fazer o link-->
                </td>
            </tr>
            {% empty %}<!--O default será o que tiver dentro da tag empty-->
            <tr>
                <td>Nenhum campo registrado.</td>
            </tr>
            {% endfor %}<!--Fechando a repetição-->
        </table>
    </div>
</div>
</div>
{% endblock %}

cadastros/templates/cadastros/lista-produto.html
{% extends 'paginas/base.html' %}

{% load static %}

{% block titulo %}
<title>Produtos ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="conteudo">
    <link rel ="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<div class="container-xl" id="container-lista">
    <div class="table table-responsive">
        <h2>Lista de Produtos:</h2>
        <hr>
        <table class="table table-striped" id="tabela">
            <tr>
                <th>Nome</th>
                <th>Quantidade no Estoque</th>
                <th>Preço Médio Total</th>
                <th>Opções</th>
            </tr>
            {% for Produto in object_list %} <!--Estrutura de repetição no django, bastante semelhante que em pyhon-->
            <tr>
                <td>
                    {{ Produto.Nome }}
                </td>
                <td>
                    {{ Produto.quantidadeTotal }} Unidades
                </td>
                <td>
                    R$ {{ Produto.precoMedioTotal }}
                </td>
                <td>
                    <a href="{% url 'Cadastro Compra' %}" class="btn btn-warning btn-sm">Comprar</a> <!--url é a forma de fazer o link-->
                    <a href="{% url 'Excluir Produto' Produto.pk %}" class="btn btn-danger btn-sm">Excluir</a>
                </td>
            </tr>
            {% empty %}<!--O default será o que tiver dentro da tag empty-->
            <tr>
                <td>Nenhum campo registrado.</td>
            </tr>
            {% endfor %}<!--Fechando a repetição-->
        </table>
    </div>
</div>
</div>
{% endblock %}

paginas/templates/paginas/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    {% block titulo %}
    <title>Inicial ::SuperMercado::</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
  </head>
  <body>
    {% block menu %}
    {% if request.user.is_authenticated %}
    <header>
      <nav class="menu-auth">
        <div class="logo-box">
          <span class="checkbtn"><i class="fas fa-bars"></i></span>
     <!--Fim Hamburguer-->
          <label class="logo"><img class="img-logo" src="{% static 'img/logo_supermarketB.png' %}"></label>
        </div>
        <div class="list-container-auth">
            <ul class="lists-auth">
                <li><a href="{% url 'index' %}" class="menu-principal">Início</a></li>
                <li>
                    <a href="#" class="menu-principal">Cadastrar</a>
                    <ul class="submenu">
                        <li class="menu-secundario"><a href="{% url 'Cadastro Produto' %}">Cadastrar Produtos</a></li>
                        <li class="menu-secundario"><a href="{% url 'Cadastro Compra' %}">Cadastrar Compras</a></li>
                    </ul>
                 </li>
                <li>
                 <a href="#" class="menu-principal">Listar</a>
                 <ul class="submenu">
                     <li class="menu-secundario"><a href="{% url 'Listar Produto' %}">Listar Produtos</a></li>
                     <li class="menu-secundario"><a href="{% url 'Listar Compra' %}">Listar Compras</a></li>
                 </ul>
             </li>
                <li>
                 <a href="{% url 'Logout' %}" class="menu-principal">Logout</a>
             </li>
             <li><span class="menu-principal"> Olá, {{ request.user }} </span></li>
            </ul>
        </div>
       </nav>
    {% else %}
        <nav class="menu">
            <div class="logo-box">
              <span class="checkbtn"><i class="fas fa-bars"></i></span>
         <!--Fim Hamburguer-->
              <label class="logo"><img class="img-logo" src="{% static 'img/logo_supermarketB.png' %}" width="270"></label>
            </div>
            <div class="list-container">
               <ul class="lists">
                   <li><a href="{% url 'index' %}">Início</a></li>
                   <li><a href="#sobrenosancora">Sobre nós</a></li>
                   <li><a href="#produtosancora">Nossos Produtos</a></li>
                   <li><a href="{% url 'Login' %}">Login</a></li>
               </ul>
            </div>
           </nav>
      </header>
      {% endif %}
      {% endblock %}

        {% block conteudo %}

        {% endblock %}

      {% block rodape %}
        <footer class="footer">
          <div class="div-footer">
            <div class="text-footer">
              <p>:: SuperMercado Batista :: | Desenvolvido por João Vitor em 2021. Site criado a fins educacionais, os direitos das imagens foram reservados. </p>
            </div>
          </div>
       </footer>
       {% endblock %}
         <!--Scripts-->
  <script src="https://kit.fontawesome.com/a7a516d8b4.js" crossorigin="anonymous"></script>
  {% if request.user.is_authenticated %}
  <script src="{% static 'js/app2.js' %}"></script>
  {% else %}
  <script src="{% static 'js/app.js' %}"></script>
  {% endif %}
  </body>
</html>

paginas/templates/paginas/index.html
{% extends 'paginas/base.html' %}

{% load static %}


{% block conteudo %}
          <div class="img-header">
            <div class="welcome">
              <h1>O melhor mercado para toda a família!</h1>
              <hr>
              <p>Não perca tempo e venha comprar com a gente!</p>
              <button class="btn-chamativo">Saiba mais</button>
            </div>
          </div>
    <section class="sobrenos" id="sobrenosancora">
      <div class="info-sobrenos">
        <h1><a></a>Mantemos o padrão de excelência em todas as unidades</h1>
        <p>Alta qualidade de produtos, tudo isso a um preço acessível ao cliente! Faça parte do nosso programa de fidelidade: ao realizar o cadastro no site você poderá fazer compras online e terá acesso a preços exclusivos. Não perca tempo, cadastre-se e compre conosco!</p>
        <div class="img-sobrenos">
          <img src="{% static 'img/img-5.jpg' %}" alt="img1">
          <img src="{% static 'img/img-9.jpg' %}" alt="img2">
          <img src="{% static 'img/img-11.jpg' %}" alt="img3">
        </div>
        <div><button class="btn-sobrenos">Cadastre-se</button></div>
      </div>
    </section>
    <section class="nossos-produtos">
      <div class="titulo-produtos" id="produtosancora">
        <h2>Novos produtos</h2>
        <hr>
      </div>
      <div class="div-produtos">
        <div class="box-produtos">
          <div class="img-produtos"><img src="{% static 'img/produto1.jpg' %}"></div>
          <div class="texto-produtos">
            <h4>Alcatra</h4>
            <p>1KG -- R$ 45,00</p>
            <div class="div-btn-prod"><button class="btn-novosprodutos">Compre já</button></div>
          </div>
        </div>
        <div class="box-produtos">
          <div class="img-produtos"><img src="{% static 'img/produto2.jpg' %}"></div>
          <div class="texto-produtos">
            <h4>Lasanha sadia</h4>
            <p>600G -- R$ 12,79</p>
            <div class="div-btn-prod"><button class="btn-novosprodutos">Compre já</button></div>
          </div>
        </div>
        <div class="box-produtos">
          <div class="img-produtos"><img src="{% static 'img/produto3.png' %}"></div>
          <div class="texto-produtos">
            <h4>Banana</h4>
            <p>Cacho -- R$ 2,50</p>
            <div class="div-btn-prod"><button class="btn-novosprodutos">Compre já</button></div>
          </div>
        </div>
        <div class="box-produtos">
          <div class="img-produtos"><img src="{% static 'img/produto4.png' %}"></div>
          <div class="texto-produtos">
            <h4>Iogurte Nestle morango</h4>
            <p>900G -- R$ 11,00</p>
            <div class="div-btn-prod"><button class="btn-novosprodutos">Compre já</button></div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

paginas/templates/paginas/navbar-user.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>AdminNavbar ::SuperMarket::</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Styles-->
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
  </head>
  <body>
    <!--Aba de menu-->
      <header>
          {% block navbar-user %}
        <!--Hamburguer-->
          <nav class="menu-auth">
            <div class="logo-box">
              <span class="checkbtn"><i class="fas fa-bars"></i></span>
         <!--Fim Hamburguer-->
              <label class="logo"><img class="img-logo" src="img/logo_supermarket.png" width="270"></label>
            </div>
            <div class="list-container-auth">
                <ul class="lists-auth">
                    <li><a href="#" class="menu-principal">Inicio</a></li>
                    <li>
                        <a href="#" class="menu-principal">Cadastrar</a>
                        <ul class="submenu">
                            <li class="menu-secundario"><a>Cadastrar Categorias</a></li>
                            <li class="menu-secundario"><a>Cadastrar Produtos</a></li>
                            <li class="menu-secundario"><a>Cadastrar Funcionários</a></li>
                        </ul>
                     </li>
                    <li>
                     <a href="#" class="menu-principal">Listar</a>
                     <ul class="submenu">
                         <li class="menu-secundario"><a>Listar Produtos</a></li>
                         <li class="menu-secundario"><a>Listar Disciplinas</a></li>
                     </ul>
                 </li>
                    <li>
                     <a href="#" class="menu-principal">Sua conta</a>
                     <ul class="submenu">
                         <li class="menu-secundario"><a>Meu Perfil</a></li>
                         <li class="menu-secundario"><a>Logout</a></li>
                     </ul>
                 </li>
                    <li><a href="#" class="menu-principal">Dashboard</a></li>
                </ul>
            </div>
           </nav>
           {% endblock %}
      </header>
         <!--Scripts-->
         <script src="https://kit.fontawesome.com/a7a516d8b4.js" crossorigin="anonymous"></script>
         <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

usuarios/templates/usuarios/login.html
{% extends 'paginas/base.html' %}

{% load static %}

{% load crispy_forms_tags %}


{% block titulo %}
<title>Login ::SuperMercado::</title>
{% endblock %}

{% block conteudo %}
<div class="formu">
    <div class="titulo-formu">
        <h1>Login</h1>
        <hr>
    </div>
    <div class="div-formu">
        <form action="" method="POST">
            {% csrf_token %}

            {{ form }}
            <div class="btn-form"><button type="submit">Enviar</button></div>
        </form> 
    </div>   
</div>

{% endblock %}